# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DotNetCoreCLI@2
  displayName: '.NET Restore'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
    feedsToUse: 'select'
- task: DotNetCoreCLI@2
  displayName: '.NET Build'
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '-c RELEASE --no-restore'
- task: DotNetCoreCLI@2
  displayName: '.NET Tests'
  inputs:
    command: 'test'
    projects: '**/*ests.csproj'
    arguments: '-c RELEASE --no-build'
- task: DotNetCoreCLI@2
  displayName: '.NET Pack'
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj'
    nobuild: true
    versioningScheme: 'byPrereleaseNumber'
    majorVersion: '1'
    minorVersion: '1'
    patchVersion: '0'
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true